### ISSUE TITLE
issue with django_admin_prod.sh

### ISSUE THREAD

**Issue by mattrwh-pC506** [domasx2/django-angular-docker-seed#13]
EDIT: I figured it out, sorry! didn't realize you needed to specific python manage.py when running managment commands in production.

When I use the django_admin_prod.sh file I get the following error.

Cannot start container 7484e80977223b670d29f8034d3a563c40cacccb81d39954ada01b9c2032c74e: [8] System error: exec: "shell": executable file not found in $PATH

Any ideas? My project has diverged somewhat so I thought it might be that I corrupted the build somehow, but when I just now pulled your most recent commit as a fresh seed project I got the same error. I ran it after running deploy.sh and start_production.sh.

**Comment by domasx2** [comment]
Yeah, this is a problem. One would reasonably expect django_admin.sh and django_admin_prod.sh to behave the same :) I will fix this
