### ISSUE TITLE
installing gulp-cli and bower causes npm to run in an infinite loop?

### ISSUE THREAD

**Issue by mattrwh-pC506** [domasx2/django-angular-docker-seed#14]
Hey, I tried launching this seed on a new box and when I run ./bin/develop.sh, on STEP 6 (the npm install gulp-cli bower -g etc. etc.) npm just runs in an infinite loop, failing to install any packages. Do you know what the issue could be? Here's a taste of the beginning of that infinite loop.

```
npm info it worked if it ends with ok
npm info using npm@2.14.4
npm info using node@v4.1.2
npm info attempt registry request try #1 at 7:08:39 PM
npm http request GET https://registry.npmjs.org/gulp-cli
npm info attempt registry request try #1 at 7:08:39 PM
npm http request GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/gulp-cli
npm info retry fetch attempt 1 at 7:08:39 PM
npm info attempt registry request try #1 at 7:08:39 PM
npm http fetch GET https://registry.npmjs.org/bower/-/bower-1.5.3.tgz
npm info retry fetch attempt 1 at 7:08:40 PM
npm info attempt registry request try #1 at 7:08:40 PM
npm http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-0.3.0.tgz
npm http fetch 200 https://registry.npmjs.org/bower/-/bower-1.5.3.tgz
npm http fetch 200 https://registry.npmjs.org/gulp-cli/-/gulp-cli-0.3.0.tgz
npm info install bower@1.5.3 into /usr/local/lib
npm info install gulp-cli@0.3.0 into /usr/local/lib
npm info installOne bower@1.5.3
npm info installOne gulp-cli@0.3.0
```

I'd appreciate the help!

Matt

**Comment by domasx2** [comment]
Hi,

I spun up a fresh digital ocean droplet w. ubuntu 14.04, installed docker-compose and ran:

``` sh
git clone https://github.com/domasx2/django-angular-docker-seed.git
cd django-angular-docker-seed
./bin/develop.sh
```

And wow, epic amount of spam from npm! But it doesn't look like there's an inifnite loop, just ridiculous logging verbosity. It took a long time ( I guess due to excessive logging?), but eventually it finished installing successfully and started as it's supposed to. 

Looks like something changed with latest npm, wasn't this spammy before. I'll investigate

Can you confirm that for you npm install gets stuck, rather than just taking a long time?

**Comment by mattrwh-pC506** [comment]
Yikes, I just assumed something was broken. I'll try now and let you know if I can get through the spam.

**Comment by domasx2** [comment]
Looks like latest node image from dockerhub has default npm loglevel set to 'info', hence the ungodly amount of spam. Pushed an update https://github.com/domasx2/django-angular-docker-seed/commit/3947c5eb6ee7f4c9d8a4250dad26acdf1031a3bf that explicitly sets loglevel to 'warn', like it used to be. Let me know if things work for you

**Comment by mattrwh-pC506** [comment]
Ah perfect, it looks like it did eventually get through it (took about 20 minutes), I'll pull the latest version and use that. Thanks for looking into it!

**Comment by domasx2** [comment]
No problem :)
