### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by felixsteghofer** [domasx2/django-angular-docker-seed#16]
Hi,
do you have a preferred method to debug the django app in this docker container?
I see there are some approaches (e.g. over ssh) but nothing really suits my needs.
Cheers

**Comment by domasx2** [comment]
Hi,  can be more specific about what kind of debugging are you talking about?

I have to confess more often than not I simply rely on copious amounts of logging :)

**Comment by felixsteghofer** [comment]
I mean in development debugging with an python debugger frontend like PyCharm (breakpoints, variable manuipulation etc.)
In the meantime I got it working with pydevd. Just for anyone who needs this:

Start the pydev server on the host (e.g. with intellij)
add pydevd to the requirements and import it in manage.py.

Then find a suitable IP address of your host and connect to it just before the django execution.

for example

**manage.py**

```
import pydevd
...
...
pydevd.settrace('192.168.0.100', port=42424, stdoutToServer=True, stderrToServer=True)
execute_from_command_line(sys.argv)
```

Thx for this very well structured development environment :)

**Comment by domasx2** [comment]
Cool, should add this to readme. Thanks :)
